### ISSUE TITLE
Found a couple holes...

### ISSUE THREAD

**Issue by T33R0** [paar5780/Arthur_CSCI2270_FinalProject#2]
I really like the premise and function of the program, it was a pretty ambitious task. The layout of the menu is logical and all of the menu options function as they should.

Some issues that I ran into:
-putting in a number for the menu that isn't an option (i.e. anything > 11) does nothing and should maybe provide an error message to the user
-more importantly, inputting a letter into the menu options creates an infinite menu print out loop
-I was unable to add myself as a patient or a donor, both resulting in "Organ not found" despite using the exact same verbage and format (Liver, Head, etc)
-because of the last bullet point and to alleviate some confusion for the user, I'd suggest that when filling out the information to add a new patient/donor there be a list for each requirement of what the options are; maybe have each credential checked for validity before moving to the next information requirement

Once again, I think the concept is great. The program serves a good purpose and can prove to be very beneficial. Good work.

**Comment by paar5780** [comment]
Thanks!
The error you ran into might be because you typed in "Heart" instead of
"heart". Someone added a feature to not make it case sensitive, so that
should be fixed now!

On Fri, May 1, 2015 at 8:16 AM, Rory Teehan notifications@github.com
wrote:

> I really like the premise and function of the program, it was a pretty
> ambitious task. The layout of the menu is logical and all of the menu
> options function as they should.
> 
> Some issues that I ran into:
> -putting in a number for the menu that isn't an option (i.e. anything >
> 11) does nothing and should maybe provide an error message to the user
> -more importantly, inputting a letter into the menu options creates an
> infinite menu print out loop
> -I was unable to add myself as a patient or a donor, both resulting in
> "Organ not found" despite using the exact same verbage and format (Liver,
> Head, etc)
> -because of the last bullet point and to alleviate some confusion for the
> user, I'd suggest that when filling out the information to add a new
> patient/donor there be a list for each requirement of what the options are;
> maybe have each credential checked for validity before moving to the next
> information requirement
> 
> Once again, I think the concept is great. The program serves a good
> purpose and can prove to be very beneficial. Good work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/paar5780/Arthur_CSCI2270_FinalProject/issues/2.

## 

Paige Anderson Arthur
University of Colorado Boulder
Aerospace Engineering
Colorado Space Grant Consortium
