### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by casamson** [paar5780/Arthur_CSCI2270_FinalProject#4]
Hey guys!

Your project is really creative and I can definitely see it being used in a real-world application. I really like the concept behind it and how you put everything that we learned this semester together in a singular project.

However, there are a few things you missed in the documentation part of the project....
- I was able to run your code by your directions, but I think you should clarify how to run it a bit more. State whether it should be compiled or not (because some people already have an executable that they run the project through so some can skip the compiling step in their projects), and if yours is c++ 11 dependent? I know that when compiling some projects, some have to be compiled with the c++ library, so specify on that to make sure others can run it!
- The methods also should have a comment block that describes the method's functionality inside the driver file itself. You guys did a great job describing what each function does in your ReadMe file, just include that in your driver file too!
- Also, include examples of how to use the code inside your driver(.cpp) file.

That should be it, I think!

Great work! Loved the project!

**Comment by Interfeller** [comment]
Thanks casamson!

We have updated the documentation on both the driver file and header file, hopefully it added some clarity. Thank you for your suggestions and kind words!
